project_name: shadab
cluster_config:
  cluster_name: eks_bimbisra_cluster
  k8s_version: 1.24
  userarn: arn:aws:iam::account_id:user/shadab
  scaling_config: 
    min_size       : 1
    max_size       : 3
    desired_size   : 1
  instance_types : ["t3a.small"]
additional_iam_role:
  - rolearn  : string
    username : string
    groups   : 
      - list(string)
  - rolearn  : string
    username : string
    groups   : 
      - list(string)  
