apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    app: app321
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app321
  template:
    metadata:
      labels: 
        app: app321
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP